config/routes.rb
Rails.application.routes.draw do
  get 'loja/index'

  resources :premios
  get 'site/index'

  resources :pontoclientes
  resources :regrapontos
  resources :pessoas
  devise_for :users
  resources :empresas
  resources :enderecos
  resources :cidades
  resources :estados
  get 'static_pages/home'
  root 'static_pages#home'
  get 'addponto', to: 'pontoclientes#addponto', as: 'addponto'
  get 'resgataponto', to: 'pontoclientes#resgatarponto', as: 'resgatarponto'
  get 'buscapremio' => 'pontoclientes#buscapremio'

  match '/listarCidade', to: 'cidades#get_cities', via: 'get'
  match '/buscaCliente', to: 'pessoas#busca_cliente', via: 'get'
  match '/buscaClientePonto', to: 'pontoclientes#busca_cliente', via: 'get'
  match '/addpontocliente', to: 'pontoclientes#add_ponto', via: 'get'
  match '/resgatapremio', to: 'pontoclientes#resgata_premio', via: 'get'
  match '/logar', to: 'userapp#login', via: 'get'
  match '/cadastrarCliente', to: 'userapp#cadastrar_cliente', via: 'get'
  match '/listaclientes', to: 'pessoas#lista_clientes', via: 'get'
  match '/showcliente', to: 'pessoas#show_cliente', via: 'get'
  match '/cadastrarUser', to: 'userapp#cadastrar_user', via: 'get'
  match '/listaempresas', to: 'empresas#lista_empresas', via: 'get'
  match '/fidelizacliente', to: 'userapp#fideliza_cliente', via: 'get'

end

app/models/pontocliente.rb
class Pontocliente < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :clienteempresa
  belongs_to :regraponto
  belongs_to :inclusao, :class_name => "User", :foreign_key => "user_inclusao"
end

app/controllers/pontoclientes_controller.rb
class PontoclientesController < ApplicationController
  before_action :set_pontocliente, only: [:show, :edit, :update, :destroy]


  def add_ponto
    if params[:empresa_id] != nil
       @empresa = params[:empresa_id]
     else
       @empresa = current_user.empresa_id
    end

    if params[:user_id] != ""
           @user = params[:user_id]
     else
           @user = current_user.id
    end

    @valor = params[:valor]
    @valorarray = @valor.split(',')

    params[:valor] = params[:valor].gsub('.', '')
    params[:valor] = params[:valor].gsub(',', '.').to_f

    @cont = 1
    @r = 0
    @c = 0

    for i in @valorarray
       if @cont == 1
         @r = i
       end
       if @cont == 2
         @c = i
       end
       @cont +=1
    end

    @valorredondo = @r.remove('.').to_i
    if @c.to_i > 0
       @valorredondo +=1
    end

     @pontocliente = Pontocliente.new
     @pontocliente.numr_ponto = @valorredondo
     @pontocliente.valor_gasto = params[:valor]
     @pontocliente.empresa_id = @empresa
     @pontocliente.clienteempresa_id = params[:id]
     @pontocliente.regraponto_id = 1
     @pontocliente.user_inclusao = @user
     @pontocliente.save

      @qdtPonto = Pontocliente.where(clienteempresa_id: params[:id]).sum(:numr_ponto)

     render :json => {:qtd => @qdtPonto, :pontoadd => @pontocliente.numr_ponto}

  end

  def resgata_premio

      # if params[:empresa_id] != nil
      #    @empresa = params[:empresa_id]
      #  else
      #    @empresa = current_user.empresa_id
      # end

      if params[:user_id] != ""
             @user = User.find(params[:user_id])
       else
             @user = current_user
      end

      @pontocliente = Pontocliente.new
      @premio = Premio.find(params[:premio_id])

      @pontocliente.numr_ponto = (-@premio.numr_ponto)
      @pontocliente.empresa_id = @user.empresa_id
      @pontocliente.clienteempresa_id = params[:id]
      @pontocliente.user_inclusao = @user.id
      @pontocliente.flag_resgatado = true
      @pontocliente.premio_id = params[:premio_id]
      @pontocliente.save

      @qdtPonto = Pontocliente.where(clienteempresa_id: params[:id]).sum(:numr_ponto)

     render :json => {:qtd => @qdtPonto}

  end


 def busca_premios
     @premios = Premio.where()
 end

  def buscapremio
    @premios = Premio.search(params[:term])
  end

  def addponto

  end

  def resgatarponto

  end

  def busca_cliente

    if params[:empresa_id] != nil
       @empresa = params[:empresa_id]
     else
       @empresa = current_user.empresa_id
    end
     @clientes = Clienteempresa.busca_cliente(params[:identificador], @empresa)

    if @clientes.empty?
       return  render :json => false
     end

    @qdtPonto = Pontocliente.where(clienteempresa_id: @clientes.first.id).sum(:numr_ponto)

    cliente_json = @clientes.map { |item| {:id => item.id,
                                         :nome => item.pessoa.nome_primeiro,
                                         :sobrenome => item.pessoa.nome_sobrenome,
                                         :cpf => item.pessoa.cpf,
                                         :codigo => item.pessoa.codigo_cliente,
                                         :qdtPonto => @qdtPonto}}

    render :json => cliente_json


  end

  # GET /pontoclientes
  # GET /pontoclientes.json
  def index
    @pontoclientes = Pontocliente.all
  end

  # GET /pontoclientes/1
  # GET /pontoclientes/1.json
  def show
  end

  # GET /pontoclientes/new
  def new
    @pontocliente = Pontocliente.new
  end

  # GET /pontoclientes/1/edit
  def edit
  end

  # POST /pontoclientes
  # POST /pontoclientes.json
  def create
    @pontocliente = Pontocliente.new(pontocliente_params)

    respond_to do |format|
      if @pontocliente.save
        format.html { redirect_to @pontocliente, notice: 'Registro incluído com suecsso.' }
        format.json { render :show, status: :created, location: @pontocliente }
      else
        format.html { render :new }
        format.json { render json: @pontocliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pontoclientes/1
  # PATCH/PUT /pontoclientes/1.json
  def update
    respond_to do |format|
      if @pontocliente.update(pontocliente_params)
        format.html { redirect_to @pontocliente, notice: 'Pontocliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @pontocliente }
      else
        format.html { render :edit }
        format.json { render json: @pontocliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pontoclientes/1
  # DELETE /pontoclientes/1.json
  def destroy
    @pontocliente.destroy
    respond_to do |format|
      format.html { redirect_to pontoclientes_url, notice: 'Pontocliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pontocliente
      @pontocliente = Pontocliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pontocliente_params
      params.require(:pontocliente).permit(:numr_ponto, :valor_gasto, :desc_ponto, :flag_resgatado, :empresa_id, :clienteempresa_id, :regraponto_id, :desc_ponto, :flag_resgatado, :user_inclusao)
    end
end

app/helpers/pontoclientes_helper.rb
module PontoclientesHelper
end

app/views/pontoclientes/_form.html.erb
<%= form_for(@pontocliente) do |f| %>
  <% if @pontocliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pontocliente.errors.count, "error") %> prohibited this pontocliente from being saved:</h2>

      <ul>
      <% @pontocliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numr_ponto %><br>
    <%= f.number_field :numr_ponto %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br>
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="field">
    <%= f.label :desc_ponto %><br>
    <%= f.text_field :desc_ponto %>
  </div>
  <div class="field">
    <%= f.label :flag_resgatado %><br>
    <%= f.check_box :flag_resgatado %>
  </div>
  <div class="field">
    <%= f.label :empresa_id %><br>
    <%= f.text_field :empresa_id %>
  </div>
  <div class="field">
    <%= f.label :clienteempresa_id %><br>
    <%= f.text_field :clienteempresa_id %>
  </div>
  <div class="field">
    <%= f.label :regraponto_id %><br>
    <%= f.text_field :regraponto_id %>
  </div>
  <div class="field">
    <%= f.label :desc_ponto %><br>
    <%= f.text_field :desc_ponto %>
  </div>
  <div class="field">
    <%= f.label :flag_resgatado %><br>
    <%= f.check_box :flag_resgatado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pontoclientes/addponto.html.erb
<section class="content">

  <div class="row">
   <div class="col-lg-6">
    <div id="Msg">
      <div class="alert alert-success" role="alert" id="msg_info">

      </div>
     </div>
    </div>
  </div>

  <div class="box box-primary">
     <div class="box-header with-border">
        <h3 class="box-title">Adicionar Pontos</h3>
      </div><!-- /.box-header -->
   <form role="form">
  <div class="box-body">

    <div class="row">
    <div class="col-md-7">

      <div class="row">
        <div class="col-lg-12">
        <div class="input-group">
          <input type="text" name="identificador" id="identificador" placeholder="Informe o CPF ou código do cliente" class="form-control input-lg">
          <span class="input-group-btn">
            <button class="btn btn-success btn-lg" type="button"  onclick="buscaCliente();">Pesquisar</button>
          </span>
        </div>
        <br>
         <input type="hidden" name="clienteempresa" id="clienteempresa">
       </div>
      </div>

      <div class="row">
        <div class="col-lg-7">
          <label>Regra</label>
          <select class="form-control input-lg">
            <option value="regra">1 Ponto 1 Real</option>
         </select>
        </div>
        <div class="col-lg-5">
          <label>Valor Gasto</label>
          <div class="input-group">
            <input type="text" name="valor" id="valor" disabled required class="form-control input-lg">
            <span class="input-group-btn" disabled>
              <button class="btn btn-success btn-lg" type="button" id="buttonadd"  onclick="add_ponto();">
                 <span class="glyphicon glyphicon-plus"></span> Incluir
              </button>
            </span>
          </div>
        </div>
       </div>

     </div>
    </div>

  <hr>

<div class="row">
 <div id="Div">
   <div class="col-lg-4">

     <h4 disabel>Cliente:</h4>
       <i id="nome_cliente"></i>
     </div>

    <div class="col-lg-4">
      <h4 disabel>Código:</h4>
      <i id="codigo_cliente"></i>
    </div>

    <div class="col-lg-4">
      <h4 disabel>Pontos acomulados:</h4>
        <i id="codigo_acomulado"></i> Pts.
    </div>

  </div>
 </div>


<br>
<br>

</div><!-- /.box -->
</form>
</div><!-- /.box-body -->
</section>

<script type="text/javascript">

 // $("#nome_cliente").text("Vanessa Freitas Valadão");

$("#Div").hide();
$("#Msg").hide();

 function buscaCliente(){
   $.ajax({
     url: '<%= buscaClientePonto_path %>',
     data : {
       identificador : $("#identificador").val()
     },
     success: function(data){

       for (var i in data) {
         var item = data[i];
          $("#clienteempresa").val(item.id);
          $("#nome_cliente").text(item.nome +" "+ item.sobrenome);
          $("#codigo_cliente").text(item.codigo);
          $("#codigo_acomulado").text(item.qdtPonto);
          $("#valor").removeAttr('disabled');
          $("#Div").show("slow")
       };
     }
   })
 };


//Foi adicionado <i id="ponto_add"></i> pontos para este cliente.

 function add_ponto(){

    if($("#valor").val() === ""){
      alert("O campo valor deve ser informado");
      return;
    }
     $.ajax({
       url: '<%= addpontocliente_path %>',
       data : {
         valor : $("#valor").val(),
         id : $("#clienteempresa").val()

       },
       success: function(data){
            $("#codigo_acomulado").text(data.qtd);
            $("#ponto_add").text(data.pontoadd)
            $("#valor").val("");
            $("#Msg").show("slow")

       }
     })

 };

 //$("msg_info").text("Teste");

 $(function() {
  $("#valor").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
})
</script>

app/views/pontoclientes/edit.html.erb
<h1>Editing Pontocliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @pontocliente %> |
<%= link_to 'Back', pontoclientes_path %>

app/views/pontoclientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pontoclientes</h1>

<table>
  <thead>
    <tr>
      <th>Numr ponto</th>
      <th>Valor gasto</th>
      <th>Desc ponto</th>
      <th>Flag resgatado</th>
      <th>Empresa</th>
      <th>Clienteempresa</th>
      <th>Regraponto</th>
      <th>Desc ponto</th>
      <th>Flag resgatado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pontoclientes.each do |pontocliente| %>
      <tr>
        <td><%= pontocliente.numr_ponto %></td>
        <td><%= pontocliente.valor_gasto %></td>
        <td><%= pontocliente.desc_ponto %></td>
        <td><%= pontocliente.flag_resgatado %></td>
        <td><%= pontocliente.empresa %></td>
        <td><%= pontocliente.clienteempresa %></td>
        <td><%= pontocliente.regraponto %></td>
        <td><%= pontocliente.desc_ponto %></td>
        <td><%= pontocliente.flag_resgatado %></td>
        <td><%= link_to 'Show', pontocliente %></td>
        <td><%= link_to 'Edit', edit_pontocliente_path(pontocliente) %></td>
        <td><%= link_to 'Destroy', pontocliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pontocliente', new_pontocliente_path %>

app/views/pontoclientes/new.html.erb
<h1>New Pontocliente</h1>

<%= render 'form' %>

<%= link_to 'Back', pontoclientes_path %>

app/views/pontoclientes/resgatarponto.html.erb
<section class="content-header">
  <div class="row">
  <div class="col-lg-6">
    <div id="Msg">
      <div class="alert alert-success" role="alert">
        O prêmio foi resgatado com sucesso
      </div>
     </div>
   </div>
  </div>
</section>

<section class="content">
  <div class="box box-primary">
     <div class="box-header with-border">
        <h3 class="box-title">Resgatar prêmio</h3>
      </div><!-- /.box-header -->
   <form role="form">
  <div class="box-body">
    <div class="row">
    <div class="col-md-6">

      <div class="row">
        <div class="col-lg-12">
        <div class="input-group">
          <input type="text" name="identificador" id="identificador" placeholder="Informe o CPF ou código do cliente" class="form-control input-lg">
          <span class="input-group-btn">
            <button class="btn btn-success btn-lg" type="button"  onclick="buscaCliente();">Pesquisar</button>
          </span>
        </div>
        <br>
         <input type="hidden" name="clienteempresa" id="clienteempresa">
       </div>
      </div>
    </div>
    </div>

<hr>
 <div id="Div">
     <div class="row">
       <div class="col-lg-4">
         <h4 disabel>Cliente:</h4>
           <i id="nome_cliente"></i>
         </div>
        <div class="col-lg-4">
          <h4 disabel>Código:</h4>
          <i id="codigo_cliente"></i>
        </div>
        <div class="col-lg-4">
          <h4 disabel>Pontos acumulados:</h4>
            <i id="codigo_acomulado"></i> Pts.
            <input type="hidden" name="ponto_acomulado"  id="ponto_acomulado">

        </div>
       <hr>
      </div>

     <hr>

     <div class="row">
         <div class="col-lg-5">
                <label>Prêmio</label>
                   <input type="text" class="form-control input-lg" id="premio" name="premio" placeholder="Pesquise pelo Prêmio">
                   <input type="hidden" name="premio_id"  id="premio_id">
                   <input type="hidden" name="ponto_resgate"  id="ponto_resgate">
         </div>
     </div>
     <hr>
     <div class="row">
        <div class="col-lg-5">
          <button type="button" class="btn btn-success btn-block btn-lg"  onclick="resgata_ponto();" name="button">Resgatar Prêmio</button>
        </div>
     </div>

</div>

<br>
<br>

</div><!-- /.box -->
</form>
</div><!-- /.box-body -->


<!-- Modal -->
<div id="ModalAviso" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Aviso <i class="glyphicon glyphicon-alert text-danger"></i></h4>
      </div>
      <div class="modal-body">
        <p>Usuário não tem pontos suficientes para resgatar esse prêmio</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
      </div>
    </div>

  </div>
</div>
</section>

<script type="text/javascript">

 // $("#nome_cliente").text("Vanessa Freitas Valadão");

$("#Div").hide();
$("#Msg").hide();

 function buscaCliente(){
   $.ajax({
     url: '<%= buscaClientePonto_path %>',
     data : {
       identificador : $("#identificador").val()
     },
     success: function(data){
       for (var i in data) {
         var item = data[i];
          $("#clienteempresa").val(item.id);
          $("#nome_cliente").text(item.nome +" "+ item.sobrenome);
          $("#codigo_cliente").text(item.codigo);
          $("#codigo_acomulado").text(item.qdtPonto);
          $("#ponto_acomulado").val(item.qdtPonto);
          $("#valor").removeAttr('disabled');
          $("#Div").show("slow")
       };
     }
   })
 };

 function add_ponto(){

    if($("#valor").val() === ""){
      alert("O campo valor deve ser informado");
      return;
    }
     $.ajax({
       url: '<%= addpontocliente_path %>',
       data : {
         valor : $("#valor").val(),
         id : $("#clienteempresa").val()
       },
       success: function(data){
            $("#codigo_acomulado").text(data.qtd);
            $("#ponto_add").text(data.pontoadd);
            $("#valor").val("");
            $("#Msg").show("slow")
       }
     })

 };

 function resgata_ponto(){

   acomulado = parseInt($("#ponto_acomulado").val());
   resgate = parseInt($("#ponto_resgate").val());

 if (acomulado >= resgate){
   $.ajax({
     url: '<%= resgatapremio_path %>',
     data : {
       premio_id : $("#premio_id").val(),
       id : $("#clienteempresa").val()
     },
     success: function(data){
          $("#codigo_acomulado").text(data.qtd);
          $("#ponto_add").text(data.pontoadd);
          $("#ponto_acomulado").val(data.qdtPonto);
          $("#valor").val("");
          $("#Msg").show("slow")
     }
   })
 }else{

   $("#ModalAviso").modal();
  // alert("Usuário não tem pontos suficientes para resgatar esse prêmio");
 }
 };

 $(document).ready(function() {
      $('#premio').autocomplete({
      source: '/buscapremio',
      dataType: 'json',
      minLength: 0,
      change: function(event, ui) {
      if (!ui.item) {
        $('#premio').val('');
      }
   },
   select: function(event, ui) {
       if (ui.item) {
             $("#premio_id").val(ui.item.id);
             $("#ponto_resgate").val(ui.item.numr_ponto);
            // codigo_acomulado
          }
        }
    });
 });

 $(function() {
  $("#valor").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
})
</script>

app/views/pontoclientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numr ponto:</strong>
  <%= @pontocliente.numr_ponto %>
</p>

<p>
  <strong>Valor gasto:</strong>
  <%= @pontocliente.valor_gasto %>
</p>

<p>
  <strong>Desc ponto:</strong>
  <%= @pontocliente.desc_ponto %>
</p>

<p>
  <strong>Flag resgatado:</strong>
  <%= @pontocliente.flag_resgatado %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @pontocliente.empresa %>
</p>

<p>
  <strong>Clienteempresa:</strong>
  <%= @pontocliente.clienteempresa %>
</p>

<p>
  <strong>Regraponto:</strong>
  <%= @pontocliente.regraponto %>
</p>

<p>
  <strong>Desc ponto:</strong>
  <%= @pontocliente.desc_ponto %>
</p>

<p>
  <strong>Flag resgatado:</strong>
  <%= @pontocliente.flag_resgatado %>
</p>

<%= link_to 'Edit', edit_pontocliente_path(@pontocliente) %> |
<%= link_to 'Back', pontoclientes_path %>