config/routes.rb
Rails.application.routes.draw do
  get 'loja/index'

  resources :premios
  get 'site/index'

  resources :pontoclientes
  resources :regrapontos
  resources :pessoas
  devise_for :users
  resources :empresas
  resources :enderecos
  resources :cidades
  resources :estados
  get 'static_pages/home'
  root 'static_pages#home'
  get 'addponto', to: 'pontoclientes#addponto', as: 'addponto'
  get 'resgataponto', to: 'pontoclientes#resgatarponto', as: 'resgatarponto'
  get 'buscapremio' => 'pontoclientes#buscapremio'

  match '/listarCidade', to: 'cidades#get_cities', via: 'get'
  match '/buscaCliente', to: 'pessoas#busca_cliente', via: 'get'
  match '/buscaClientePonto', to: 'pontoclientes#busca_cliente', via: 'get'
  match '/addpontocliente', to: 'pontoclientes#add_ponto', via: 'get'
  match '/resgatapremio', to: 'pontoclientes#resgata_premio', via: 'get'
  match '/logar', to: 'userapp#login', via: 'get'
  match '/cadastrarCliente', to: 'userapp#cadastrar_cliente', via: 'get'
  match '/listaclientes', to: 'pessoas#lista_clientes', via: 'get'
  match '/showcliente', to: 'pessoas#show_cliente', via: 'get'
  match '/cadastrarUser', to: 'userapp#cadastrar_user', via: 'get'
  match '/listaempresas', to: 'empresas#lista_empresas', via: 'get'
  match '/fidelizacliente', to: 'userapp#fideliza_cliente', via: 'get'

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
  belongs_to :estado
end

app/models/clienteempresa.rb
class Clienteempresa < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :pessoa


  def self.busca_cliente(indent, empresa)
    sql = " INNER JOIN pessoas pe on pessoa_id = pe.id"
    sql = sql + " WHERE empresa_id = #{empresa}"
    sql = sql + " AND (pe.cpf = '#{indent}' OR pe.codigo_cliente = #{indent})"
    self.joins(sql)
  end

end

app/models/contcodigocliente.rb
class Contcodigocliente < ActiveRecord::Base

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  belongs_to :endereco, dependent: :destroy

  accepts_nested_attributes_for :endereco, allow_destroy: true

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/empresa1.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  belongs_to :cidade
end

app/models/estado.rb
class Estado < ActiveRecord::Base
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  belongs_to :endereco, dependent: :destroy
  belongs_to :inclusao, :class_name => "User", :foreign_key => "user_inclusao"

  accepts_nested_attributes_for :endereco, allow_destroy: true

  SEXO = %w[Masculino Feminino]

  before_create  :geraCodigo
  after_create   :atualizaContador

  def  geraCodigo
  @@contcliente = Contcodigocliente.find(1)
  @@codigo = @@contcliente.codigo
  @@codigo += 1
  self.codigo_cliente  = @@codigo

 end

 def  atualizaContador
    @@contcliente.update(:codigo => @@codigo)
 end

end

app/models/pontocliente.rb
class Pontocliente < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :clienteempresa
  belongs_to :regraponto
  belongs_to :inclusao, :class_name => "User", :foreign_key => "user_inclusao"
end

app/models/premio.rb
class Premio < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :inclusao, :class_name => "User", :foreign_key => "user_inclusao"
  belongs_to :exclusao, :class_name => "User", :foreign_key => "user_exclusao"


  def self.search(term)
    where("lower(nome_premio)like ?", "%#{term.downcase}%")
  end

end

app/models/regraponto.rb
class Regraponto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :pessoa
  belongs_to :empresa

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/regrapontos_controller.rb
class RegrapontosController < ApplicationController
  before_action :set_regraponto, only: [:show, :edit, :update, :destroy]


  # GET /regrapontos
  # GET /regrapontos.json
  def index
    @regrapontos = Regraponto.all
  end

  # GET /regrapontos/1
  # GET /regrapontos/1.json
  def show
  end

  # GET /regrapontos/new
  def new
    @regraponto = Regraponto.new
  end

  # GET /regrapontos/1/edit
  def edit
  end

  # POST /regrapontos
  # POST /regrapontos.json
  def create
    @regraponto = Regraponto.new(regraponto_params)

    respond_to do |format|
      if @regraponto.save
        format.html { redirect_to @regraponto, notice: 'Regraponto was successfully created.' }
        format.json { render :show, status: :created, location: @regraponto }
      else
        format.html { render :new }
        format.json { render json: @regraponto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regrapontos/1
  # PATCH/PUT /regrapontos/1.json
  def update
    respond_to do |format|
      if @regraponto.update(regraponto_params)
        format.html { redirect_to @regraponto, notice: 'Regraponto was successfully updated.' }
        format.json { render :show, status: :ok, location: @regraponto }
      else
        format.html { render :edit }
        format.json { render json: @regraponto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regrapontos/1
  # DELETE /regrapontos/1.json
  def destroy
    @regraponto.destroy
    respond_to do |format|
      format.html { redirect_to regrapontos_url, notice: 'Regraponto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regraponto
      @regraponto = Regraponto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regraponto_params
      params.require(:regraponto).permit(:nome_regra)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/loja_helper.rb
module LojaHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/premios_helper.rb
module PremiosHelper
end

app/helpers/regrapontos_helper.rb
module RegrapontosHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/userapp_helper.rb
module UserappHelper
end

app/views/regrapontos/_form.html.erb
<%= form_for(@regraponto) do |f| %>
  <% if @regraponto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regraponto.errors.count, "error") %> prohibited this regraponto from being saved:</h2>

      <ul>
      <% @regraponto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_regra %><br>
    <%= f.text_field :nome_regra %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regrapontos/edit.html.erb
<h1>Editing Regraponto</h1>

<%= render 'form' %>

<%= link_to 'Show', @regraponto %> |
<%= link_to 'Back', regrapontos_path %>

app/views/regrapontos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regrapontos</h1>

<table>
  <thead>
    <tr>
      <th>Nome regra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regrapontos.each do |regraponto| %>
      <tr>
        <td><%= regraponto.nome_regra %></td>
        <td><%= link_to 'Show', regraponto %></td>
        <td><%= link_to 'Edit', edit_regraponto_path(regraponto) %></td>
        <td><%= link_to 'Destroy', regraponto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Regraponto', new_regraponto_path %>

app/views/regrapontos/new.html.erb
<h1>New Regraponto</h1>

<%= render 'form' %>

<%= link_to 'Back', regrapontos_path %>

app/views/regrapontos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome regra:</strong>
  <%= @regraponto.nome_regra %>
</p>

<%= link_to 'Edit', edit_regraponto_path(@regraponto) %> |
<%= link_to 'Back', regrapontos_path %>